#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShopDiaryProjectV1.Resource", IsApplication=true)]

namespace ShopDiaryProjectV1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ShopDiaryProjectV1.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ShopDiaryProjectV1.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ShopDiaryProjectV1.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Category = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Location = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int StorageRumah1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int StorageRumah2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int StorageRumah3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int StorageRumah4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int StorageRumah5 = 2131034118;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int calendar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int garbage = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iconBack = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iconMenu = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logoshopdiary = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menuAdd = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int MenuCategory = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menuPlace = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menuRunOut = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menuShoplist = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int menuStorage = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menuSummary = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int menuUse = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int SCJZO = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int storage = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int use = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070043
			public const int btnAddBack1 = 2131165251;
			
			// aapt resource value: 0x7f07004a
			public const int btnAddBack2 = 2131165258;
			
			// aapt resource value: 0x7f070062
			public const int btnDrawerAdd = 2131165282;
			
			// aapt resource value: 0x7f070060
			public const int btnDrawerBack = 2131165280;
			
			// aapt resource value: 0x7f070066
			public const int btnDrawerCategory = 2131165286;
			
			// aapt resource value: 0x7f070061
			public const int btnDrawerPlace = 2131165281;
			
			// aapt resource value: 0x7f070065
			public const int btnDrawerRunOut = 2131165285;
			
			// aapt resource value: 0x7f070067
			public const int btnDrawerShopList = 2131165287;
			
			// aapt resource value: 0x7f070064
			public const int btnDrawerStorage = 2131165284;
			
			// aapt resource value: 0x7f070068
			public const int btnDrawerSummary = 2131165288;
			
			// aapt resource value: 0x7f070063
			public const int btnDrawerUse = 2131165283;
			
			// aapt resource value: 0x7f07007b
			public const int btnMainAdd = 2131165307;
			
			// aapt resource value: 0x7f07007c
			public const int btnMainKart = 2131165308;
			
			// aapt resource value: 0x7f07006e
			public const int btnMainMenu = 2131165294;
			
			// aapt resource value: 0x7f07007d
			public const int btnMainRunOut = 2131165309;
			
			// aapt resource value: 0x7f070079
			public const int btnMainStorage = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int btnMainUse = 2131165306;
			
			// aapt resource value: 0x7f070054
			public const int btnPageAddWithoutScanExpDate = 2131165268;
			
			// aapt resource value: 0x7f0700a1
			public const int btnUseBack = 2131165345;
			
			// aapt resource value: 0x7f070082
			public const int button1 = 2131165314;
			
			// aapt resource value: 0x7f070085
			public const int button2 = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int button3 = 2131165318;
			
			// aapt resource value: 0x7f070056
			public const int buttonAddAddToInventory = 2131165270;
			
			// aapt resource value: 0x7f070055
			public const int buttonAddExpDate = 2131165269;
			
			// aapt resource value: 0x7f070033
			public const int buttonAddExpDateOk = 2131165235;
			
			// aapt resource value: 0x7f07001c
			public const int buttonAddLocationAdd = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int buttonAddLocationCancel = 2131165213;
			
			// aapt resource value: 0x7f070047
			public const int buttonAddScan1 = 2131165255;
			
			// aapt resource value: 0x7f070058
			public const int buttonAddScan2 = 2131165272;
			
			// aapt resource value: 0x7f070027
			public const int buttonAddStorageCancel = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int buttonAddStorageOK = 2131165222;
			
			// aapt resource value: 0x7f070048
			public const int buttonAddWithoutScan1 = 2131165256;
			
			// aapt resource value: 0x7f070059
			public const int buttonAddWithoutScan2 = 2131165273;
			
			// aapt resource value: 0x7f07005c
			public const int buttonCategoriesAdd = 2131165276;
			
			// aapt resource value: 0x7f07005a
			public const int buttonCategoriesBack = 2131165274;
			
			// aapt resource value: 0x7f07005e
			public const int buttonCategoriesDelete = 2131165278;
			
			// aapt resource value: 0x7f07005d
			public const int buttonCategoriesEdit = 2131165277;
			
			// aapt resource value: 0x7f07002b
			public const int buttonCategoryDetailCancel = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int buttonCategoryDetailEdit = 2131165226;
			
			// aapt resource value: 0x7f070030
			public const int buttonLocDetailDelete = 2131165232;
			
			// aapt resource value: 0x7f07002f
			public const int buttonLocDetailEdit = 2131165231;
			
			// aapt resource value: 0x7f070080
			public const int buttonLocationAdd = 2131165312;
			
			// aapt resource value: 0x7f07007e
			public const int buttonLocationBack = 2131165310;
			
			// aapt resource value: 0x7f070031
			public const int buttonLocationDetailCancel = 2131165233;
			
			// aapt resource value: 0x7f070081
			public const int buttonLocationEdit = 2131165313;
			
			// aapt resource value: 0x7f07006c
			public const int buttonMainLogin = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int buttonMainRegister = 2131165293;
			
			// aapt resource value: 0x7f07003a
			public const int buttonRegisterOK = 2131165242;
			
			// aapt resource value: 0x7f0700a5
			public const int buttonSearchUse = 2131165349;
			
			// aapt resource value: 0x7f070071
			public const int buttonSendNotif = 2131165297;
			
			// aapt resource value: 0x7f07008e
			public const int buttonStorageAdd = 2131165326;
			
			// aapt resource value: 0x7f070090
			public const int buttonStorageDelete = 2131165328;
			
			// aapt resource value: 0x7f07008f
			public const int buttonStorageEdit = 2131165327;
			
			// aapt resource value: 0x7f070041
			public const int buttonStoreDetailCancel = 2131165249;
			
			// aapt resource value: 0x7f070040
			public const int buttonStoreDetailOk = 2131165248;
			
			// aapt resource value: 0x7f070097
			public const int buttonSummaryOk = 2131165335;
			
			// aapt resource value: 0x7f0700a8
			public const int buttonUseDelete = 2131165352;
			
			// aapt resource value: 0x7f0700a7
			public const int buttonUseUse = 2131165351;
			
			// aapt resource value: 0x7f0700ab
			public const int buttonZxing = 2131165355;
			
			// aapt resource value: 0x7f070044
			public const int cameraPreview = 2131165252;
			
			// aapt resource value: 0x7f0700aa
			public const int contentFrame = 2131165354;
			
			// aapt resource value: 0x7f070032
			public const int datePickerAddExpDate = 2131165234;
			
			// aapt resource value: 0x7f070036
			public const int editText1 = 2131165238;
			
			// aapt resource value: 0x7f070039
			public const int editText2 = 2131165241;
			
			// aapt resource value: 0x7f070015
			public const int editTextAddLocationAddress = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int editTextAddLocationDesc = 2131165209;
			
			// aapt resource value: 0x7f070011
			public const int editTextAddLocationName = 2131165201;
			
			// aapt resource value: 0x7f07004d
			public const int editTextAddName = 2131165261;
			
			// aapt resource value: 0x7f070053
			public const int editTextAddPrice = 2131165267;
			
			// aapt resource value: 0x7f070022
			public const int editTextAddStorageArea = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int editTextAddStorageBlock = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int editTextAddStorageDesc = 2131165221;
			
			// aapt resource value: 0x7f07001f
			public const int editTextAddStorageName = 2131165215;
			
			// aapt resource value: 0x7f070029
			public const int editTextCategoryDetailDescription = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int editTextCategoryDetailName = 2131165224;
			
			// aapt resource value: 0x7f07002d
			public const int editTextLocationDetailAddress = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int editTextLocationDetailDescription = 2131165230;
			
			// aapt resource value: 0x7f07002c
			public const int editTextLocationDetailName = 2131165228;
			
			// aapt resource value: 0x7f070035
			public const int editTextRegEmail = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int editTextRegUser = 2131165236;
			
			// aapt resource value: 0x7f07003c
			public const int editTextStorDetailArea = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int editTextStorDetailBlock = 2131165246;
			
			// aapt resource value: 0x7f07003b
			public const int editTextStorageDetailName = 2131165243;
			
			// aapt resource value: 0x7f07003f
			public const int editTextStoreDetailDescription = 2131165247;
			
			// aapt resource value: 0x7f070084
			public const int imageButton1 = 2131165316;
			
			// aapt resource value: 0x7f070092
			public const int imageButtonPageSummaryBack = 2131165330;
			
			// aapt resource value: 0x7f070089
			public const int imageButtonStorageBack = 2131165321;
			
			// aapt resource value: 0x7f070096
			public const int imageButtonSummaryEndDate = 2131165334;
			
			// aapt resource value: 0x7f070094
			public const int imageButtonSummaryStartDate = 2131165332;
			
			// aapt resource value: 0x7f070069
			public const int imageView1 = 2131165289;
			
			// aapt resource value: 0x7f07006f
			public const int imageView2 = 2131165295;
			
			// aapt resource value: 0x7f0700ac
			public const int imageViewZxing = 2131165356;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f0700a2
			public const int linearLayout10 = 2131165346;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout2 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout3 = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout4 = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout5 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout6 = 2131165211;
			
			// aapt resource value: 0x7f07003d
			public const int linearLayout7 = 2131165245;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayout8 = 2131165263;
			
			// aapt resource value: 0x7f07004b
			public const int linearLayout9 = 2131165259;
			
			// aapt resource value: 0x7f070046
			public const int linearMenuQuick = 2131165254;
			
			// aapt resource value: 0x7f070042
			public const int main_content = 2131165250;
			
			// aapt resource value: 0x7f070087
			public const int recyclerView1 = 2131165319;
			
			// aapt resource value: 0x7f07005f
			public const int recyclerViewCategories = 2131165279;
			
			// aapt resource value: 0x7f070078
			public const int recyclerViewInventoryMainPage = 2131165304;
			
			// aapt resource value: 0x7f070083
			public const int recyclerViewLocations = 2131165315;
			
			// aapt resource value: 0x7f070091
			public const int recyclerViewStorages = 2131165329;
			
			// aapt resource value: 0x7f0700a9
			public const int recyclerViewUse = 2131165353;
			
			// aapt resource value: 0x7f0700a4
			public const int searchBoxUse = 2131165348;
			
			// aapt resource value: 0x7f07004e
			public const int spinnerAddItemCategory = 2131165262;
			
			// aapt resource value: 0x7f070052
			public const int spinnerAddItemStorage = 2131165266;
			
			// aapt resource value: 0x7f0700a3
			public const int spinnerUseStorageSelected = 2131165347;
			
			// aapt resource value: 0x7f07006b
			public const int textBoxMainPassword = 2131165291;
			
			// aapt resource value: 0x7f07006a
			public const int textBoxUsername = 2131165290;
			
			// aapt resource value: 0x7f07001e
			public const int textMainADDSTORAGE = 2131165214;
			
			// aapt resource value: 0x7f070075
			public const int textMainExpCount = 2131165301;
			
			// aapt resource value: 0x7f070072
			public const int textMainExpired = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int textMainRunOut = 2131165299;
			
			// aapt resource value: 0x7f070076
			public const int textMainRunOutCount = 2131165302;
			
			// aapt resource value: 0x7f070074
			public const int textMainStock = 2131165300;
			
			// aapt resource value: 0x7f070077
			public const int textMainStockCount = 2131165303;
			
			// aapt resource value: 0x7f070020
			public const int textNameAddStorage = 2131165216;
			
			// aapt resource value: 0x7f070045
			public const int textScannedBarcode = 2131165253;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f070050
			public const int textView10 = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int textView11 = 2131165265;
			
			// aapt resource value: 0x7f070099
			public const int textView12 = 2131165337;
			
			// aapt resource value: 0x7f07009b
			public const int textView13 = 2131165339;
			
			// aapt resource value: 0x7f07009c
			public const int textView14 = 2131165340;
			
			// aapt resource value: 0x7f07009e
			public const int textView15 = 2131165342;
			
			// aapt resource value: 0x7f07009f
			public const int textView16 = 2131165343;
			
			// aapt resource value: 0x7f07000f
			public const int textView2 = 2131165199;
			
			// aapt resource value: 0x7f0700a0
			public const int textView20 = 2131165344;
			
			// aapt resource value: 0x7f070010
			public const int textView3 = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int textView4 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int textView5 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int textView6 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int textView7 = 2131165208;
			
			// aapt resource value: 0x7f070037
			public const int textView8 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int textView9 = 2131165240;
			
			// aapt resource value: 0x7f070003
			public const int textViewAdapterCategoryDescription = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int textViewAdapterCategoryName = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int textViewAdapterLocationAddress = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textViewAdapterLocationDescription = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int textViewAdapterLocationName = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int textViewAdapterStorageArea = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textViewAdapterStorageBlock = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int textViewAdapterStorageDescription = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int textViewAdapterStorageName = 2131165194;
			
			// aapt resource value: 0x7f07004c
			public const int textViewAddBarcodeId = 2131165260;
			
			// aapt resource value: 0x7f070023
			public const int textViewAddStorageBlock = 2131165219;
			
			// aapt resource value: 0x7f070070
			public const int textViewCurrentLocationMainPage = 2131165296;
			
			// aapt resource value: 0x7f070095
			public const int textViewEndDate = 2131165333;
			
			// aapt resource value: 0x7f070098
			public const int textViewItemAdded = 2131165336;
			
			// aapt resource value: 0x7f070006
			public const int textViewMainListExpDate = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int textViewMainListName = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textViewMainListStatus = 2131165189;
			
			// aapt resource value: 0x7f07007f
			public const int textViewManageLocationSelectedLocation = 2131165311;
			
			// aapt resource value: 0x7f07008a
			public const int textViewManageStoragess = 2131165322;
			
			// aapt resource value: 0x7f07009a
			public const int textViewMoneySpent = 2131165338;
			
			// aapt resource value: 0x7f07009d
			public const int textViewMoneySpentOnExpiredItem = 2131165341;
			
			// aapt resource value: 0x7f07005b
			public const int textViewSelectedCategory = 2131165275;
			
			// aapt resource value: 0x7f07008d
			public const int textViewSelectedStorage = 2131165325;
			
			// aapt resource value: 0x7f070093
			public const int textViewStartDate = 2131165331;
			
			// aapt resource value: 0x7f07008b
			public const int textViewStoragePicked = 2131165323;
			
			// aapt resource value: 0x7f07008c
			public const int textViewStoragestitik2 = 2131165324;
			
			// aapt resource value: 0x7f0700a6
			public const int textViewUseSelectedItem = 2131165350;
			
			// aapt resource value: 0x7f070021
			public const int textViewsemiColomAddStorageArea = 2131165217;
			
			// aapt resource value: 0x7f070049
			public const int toolbarAddWithoutScan = 2131165257;
			
			// aapt resource value: 0x7f070088
			public const int toolbarStorages = 2131165320;
			
			// aapt resource value: 0x7f070057
			public const int toolbarWithoutScanBottom = 2131165271;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterCategories = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AdapterItemStatusMain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AdapterLocations = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AdapterStorages = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CustomBarcodeLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DialogAddLocation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DialogAddStorage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int DialogCategoryDetail = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int DialogLocationDetail = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DialogPageDatePicker = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int DialogPageRegister = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int DialogStorageDetail = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int PageAdd = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PageAddWithoutScan = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PageCategories = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PageDrawerMenu = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PageLogin = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PageMainStart = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PageManagePlace = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int PageShopList = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int PageStorages = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int PageSummary = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int PageUse = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int zxingscanneractivitylayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int zxingscannerfragmentlayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ZxingSurfaceScanner = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public const int FormTextTheme = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int FormTheme = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int ImageButton = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int LoginPageButton = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int LoginPageTextBoxTheme = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TextTheme = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int TextView = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
